### ISSUE TITLE
SQL disable upprecase conversion

### ISSUE THREAD

**Issue by nodermann** [igorcoding/asynctnt#13]
Simple query:

```sql
SELECT COUNT(favorite) FROM "table1" WHERE  favorite = 1;
```

got exception:
```bash
asynctnt.exceptions.TarantoolDatabaseError: (176, "Can’t resolve field 'FAVORITE'")
```

I know that can do like that and it will be ok:

```sql
SELECT COUNT("favorite") FROM "table1" WHERE  "favorite" = 1;
```

but I would like good syntax, no conversion to uppercase, does it make sense?

**Comment by igorcoding** [comment]
It's not an issue of asynctnt. Asynctnt does not perform any conversion. The problem is that Tarantool assumes all columns are SQL ANSI-compilant so it transforms them to uppercase. The only possible way is to use quotes. Btw, if you created a space using `create table` statement then all the columns would automatically be in uppercase
